buildscript {
    repositories {
        maven {
            url "https://plugins.gradle.org/m2/"
        }
    }
    dependencies {
        classpath "com.gradle.publish:plugin-publish-plugin:0.9.1"
    }
}

apply plugin: 'groovy'
apply plugin: 'maven-publish'
apply plugin: 'eclipse'
apply plugin: "com.gradle.plugin-publish"

defaultTasks 'build'

group = project.hasProperty('group') ? project.group : 'org.spongepowered'
version = project.hasProperty('version') ? project.version : (buildVersion + (buildType == 'RELEASE' ? '' : "-$buildType"))
base {
    archivesName = "mixingradle"
}

[compileJava, compileTestJava]*.options*.encoding = 'UTF-8'
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(8)
    }
}

repositories {
    mavenCentral()
}

dependencies {
    implementation gradleApi()
    implementation 'com.google.guava:guava:17.0'
    implementation 'org.ow2.asm:asm-debug-all:5.0.3'
}

processResources {
   from 'LICENSE.txt'
}

jar.manifest.mainAttributes (
    "Built-By": System.properties['user.name'],
    "Created-By": System.properties['java.vm.version'] + " (" + System.properties['java.vm.vendor'] + ")",
    "Implementation-Title": name,
    "Implementation-Version": version
)

task groovydocJar(type: Jar, dependsOn: groovydoc) {
    from groovydoc.destinationDir
    archiveClassifier = 'groovydoc'
}

artifacts {
    archives jar
    archives groovydocJar
}

pluginBundle {
    website = 'http://www.gradle.org/'
    vcsUrl = 'https://github.com/SpongePowered/MixinGradle'
    description = 'Gradle plugin for SpongePowered Mixin'
    tags = ['spongepowered', 'sponge', 'mixin']
    plugins {
        patcher {
            id = 'org.spongepowered.mixin'
            displayName = 'SpongePowered Mixin Gradle Plugin'
        }
    }
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
            artifact groovydocJar

            groupId = project.group
            artifactId = project.base.archivesName.get()
            version = project.version

            pom {
                name = project.base.archivesName.get()
                packaging = 'jar'
                description = 'MixinGradle'
                url = 'http://www.spongepowered.org/'

                scm {
                    url = 'https://github.com/SpongePowered/MixinGradle'
                    connection = 'scm:git:git://github.com/SpongePowered/MixinGradle.git'
                    developerConnection = 'scm:git:git@github.com:SpongePowered/MixinGradle.git'
                }

                issueManagement {
                    system = 'GitHub Issues'
                    url = 'https://github.com/SpongePowered/MixinGradle/issues'
                }

                licenses {
                    license {
                        name = 'MIT license'
                        url = 'http://opensource.org/licenses/MIT'
                        distribution = 'repo'
                    }
                }
            }
        }
    }
    repositories {
        mavenLocal()
        if (project.hasProperty("chRepo")) {
            maven {
                url = project.chRepo
                credentials {
                    username = project.chUsername
                    password = project.chPassword
                }
            }
        }
    }
}
